accounts/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from . import views, forms

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(template_name='accounts/login.html', authentication_form=forms.UserLoginForm), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='view_profile'),
    url(r'^profile/edit/$', views.EditProfileView.as_view(), name='edit_profile'),
    url(r'^profile/password/$', views.ProfilePasswordChangeView.as_view(), name='change_password'),
]

connectors/urls.py
from django.conf.urls import url
from . import views, viewsets

app_name = 'connectors'

urlpatterns = [
    url(r'^$', views.ConnectorListView.as_view(), name='list'),
    url(r'^create/$', views.CreateConnectorView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.UpdateConnectorView.as_view(), name='update'),
    url(r'^api/$', viewsets.ConnectorAPIView.as_view(), name='api_list'),
]

datasets/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views, viewsets

app_name = 'datasets'

urlpatterns = [
    url(r'^$', views.DatasetListView.as_view(), name='list'),
    url(r'^import/$', TemplateView.as_view(template_name='datasets/create_dataset.html'), name='import'),
    url(r'^upload/$', views.DataImportView.as_view(), name="upload"),
    url(r'^connector/$', TemplateView.as_view(template_name='datasets/choose_connector.html'), name="connector"),
    url(r'^api/query/$', viewsets.QueryAPIView.as_view(), name='api_query'),
    url(r'^query/$', views.QueryView.as_view(), name='query'),
    url(r'^api/preview/$', viewsets.PreviewAPIView.as_view(), name="api_preview"),
    url(r'^preview/$', views.PreviewView.as_view(), name="preview"),
    url(r'^preview/cancel/$', views.ImportCancelView.as_view(), name="cancel"),
    url(r'^(?P<pk>\d+)/$', views.DataDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/delete/$', views.DataDeleteView.as_view(), name="delete"),
]

trigrams/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as root_views

urlpatterns = [
    url(r'^$', root_views.login_redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^connectors/', include('connectors.urls')),
    url(r'^datasets/', include('datasets.urls')),
]

datasets/models.py
from django.contrib.auth.models import User
from django.db import models
from connectors.models import Connector


class Dataset(models.Model):
    dataset_name = models.CharField(max_length=40)
    display_name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    schema = models.TextField()
    owner = models.ForeignKey(User)
    sep = models.CharField(max_length=3, blank=True)
    external = models.BooleanField(default=False)
    dataset_type = models.CharField(max_length=10)
    encoding = models.CharField(max_length=20, blank=True)
    connector = models.ForeignKey(Connector, on_delete=models.CASCADE, blank=True, null=True)
    query_string = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.display_name


class Table(models.Model):
    columns = models.TextField()
    sample = models.TextField()
    schema = models.TextField()

datasets/forms.py
from django import forms
from .models import Dataset


class FileUploadForm(forms.Form):
    file = forms.FileField(widget=forms.FileInput(attrs={
        'class': 'form-control',
    }))

    class Meta:
        fields = '__all__'


class PreviewForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = [
            'display_name',
            'description',
            'encoding',
            'sep',
            'schema',
        ]


class QueryForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = [
            'display_name',
            'description',
            'query_string',
            'schema',
        ]

datasets/views.py
import os, uuid
from datetime import datetime
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.base import RedirectView
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from sqlalchemy.exc import DBAPIError

from connectors.utils import create_connection
from trigrams import settings
from connectors.models import Connector
from .models import Dataset
from .forms import FileUploadForm, PreviewForm, QueryForm
from .utils import SourceParser


class DatasetListView(LoginRequiredMixin, ListView):
    context_object_name = 'dataset_list'
    login_url = reverse_lazy('accounts:login')

    def get_queryset(self):
        return Dataset.objects.filter(owner=self.request.user)


class DataDeleteView(LoginRequiredMixin, DeleteView):
    model = Dataset
    success_url = reverse_lazy('datasets:list')
    login_url = reverse_lazy('accounts:login')

    def delete(self, request, *args, **kwargs):
        instance = self.get_object()
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, instance.dataset_name)):
            os.remove(os.path.join(settings.MEDIA_ROOT, instance.dataset_name))
        return super(DataDeleteView, self).delete(request, *args, **kwargs)


class DataDetailView(LoginRequiredMixin, DetailView):
    model = Dataset
    login_url = reverse_lazy('accounts:login')

    def get_context_data(self, **kwargs):
        context = super(DataDetailView, self).get_context_data(**kwargs)
        if self.object.external:
            connection = self.create_connection_from_connector()
            columns, content, dtype, count = SourceParser.query_sql(self.object.query_string, connection)
        else:
            columns, content, dtype, count = SourceParser.read_csv(self.object.dataset_name,
                                                                   sep=self.object.sep,
                                                                   encoding=self.object.encoding)
        context['columns'] = columns
        context['sample'] = content
        context['total_count'] = count
        return context

    def create_connection_from_connector(self):
        connector = self.object.connector
        try:
            return create_connection(db_type=connector.db_type,
                                     host=connector.host,
                                     port=connector.port,
                                     user=connector.username,
                                     password=connector.password,
                                     db_instance=connector.db_instance)
        except DBAPIError as err:
            print(err.args)


class DataImportView(LoginRequiredMixin, FormView):
    template_name = 'datasets/upload_file.html'
    form_class = FileUploadForm
    login_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        self.save_uploaded_file(self.request.FILES['file'])
        return super(DataImportView, self).form_valid(form)

    def save_uploaded_file(self, f):
        self.display_name, self.extension = os.path.splitext(f.name)
        self.file_name = str(uuid.uuid5(uuid.NAMESPACE_DNS, str(datetime.now())))
        with open(os.path.join(settings.MEDIA_ROOT, self.file_name), 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

    def get_success_url(self):
        self.extension = self.extension.lower()
        if self.extension == '.txt':
            self.extension = '.csv'
        return reverse('datasets:preview') + '?file_name=' + self.file_name\
               + '&display_name=' + self.display_name + '&extension=' + self.extension


class ImportCancelView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('datasets:list')
    permanent = False
    login_url = reverse_lazy('accounts:login')

    def get_redirect_url(self, *args, **kwargs):
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, self.request.GET.get('file_name'))):
            os.remove(os.path.join(settings.MEDIA_ROOT, self.request.GET.get('file_name')))
        return super(ImportCancelView, self).get_redirect_url(*args, **kwargs)


class PreviewView(LoginRequiredMixin, CreateView):
    template_name = 'datasets/preview.html'
    login_url = reverse_lazy('accounts:login')
    form_class = PreviewForm

    def get_success_url(self):
        return reverse('datasets:list')

    def get_context_data(self, **kwargs):
        context = super(PreviewView, self).get_context_data(**kwargs)
        context['display_name'] = self.request.GET.get('display_name')
        context['file_name'] = self.request.GET.get('file_name')
        context['dtype'] = self.request.GET.get('dtype')
        context['encoding'] = self.request.GET.get('encoding', 'utf-8')
        context['description'] = self.request.GET.get('description', '')
        if self.request.GET.get('extension') == '.csv':
            context['sep'] = self.request.GET.get('sep', ',')
        else:
            context['sheet_name'] = self.request.GET.get('sheet_name')
        context['extension'] = self.request.GET.get('extension')
        return context

    def form_valid(self, form):
        dataset = form.save(commit=False)
        dataset.dataset_name = self.request.GET.get('file_name')
        dataset.owner = self.request.user
        dataset.save()
        return super(PreviewView, self).form_valid(form)


class QueryView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'datasets/query.html'
    form_class = QueryForm

    def get_success_url(self):
        return reverse('datasets:list')

    def get_context_data(self, **kwargs):
        context = super(QueryView, self).get_context_data(**kwargs)
        context['conn_name'] = self.request.GET.get('conn_name')
        context['display_name'] = self.request.GET.get('display_name') if 'display_name' in self.request.GET else 'Untitiled name'
        return context

    def form_valid(self, form):
        connector = get_object_or_404(Connector, conn_name=self.request.GET.get('conn_name'))
        dataset = form.save(commit=False)
        dataset.connector = connector
        dataset.owner = self.request.user
        dataset.external = True
        dataset.dataset_name = str(uuid.uuid5(uuid.NAMESPACE_DNS, str(datetime.now())))
        dataset.save()
        return super(QueryView, self).form_valid(form)

datasets/templates/datasets/choose_connector.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}New Data set{% endblock %}

{% block nav-title %}<h3>Connector</h3>{% endblock %}

{% block linkblock %}
{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a href="{% url 'connectors:create' %}" class="nav-link btn btn-primary">
                <i class="ti-plus"></i>&nbsp;
                <span class="d-lg-block">{% trans 'New' %}</span>
            </a>
        </li>
    </ul>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-5 col-sm-12">
            <div class="card">
                <div class="card-header">
                    {% block breadcrumb %}
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'datasets:import' %}">Type</a></li>
                                <li class="breadcrumb-item">Connector</li>
                                <li class="breadcrumb-item active">Query</li>
                            </ol>
                        </nav>
                    {% endblock %}
                </div>
                <div class="card-body">
                    <div class="connector-list"></div>
                </div>
                <div class="card-footer">
                    <a id="conn-select" disabled="false" class="btn btn-primary">{% trans 'Select' %}</a>
                </div>
            </div>
        </div>
        <div class="col-md-5 col-sm-12">
            <div class="card">
                <div class="col-12">
                    <div class="connector-info">
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scriptblock %}
<script>
$(document).ready(function () {
    $.get("{% url 'connectors:api_list' %}",
            function (data, status) {
                for (var idx in data) {
                    var buttonTag = $('<button/>');
                    buttonTag.addClass('btn btn-con form-control')
                            .html(data[idx].conn_name)
                            .on('click',
                                {
                                    conn_name: data[idx].conn_name,
                                    idx: idx
                                },
                                function (event) {
                                    $('#conn-select').attr('href', '{% url "datasets:query" %}' + '?conn_name=' + event.data.conn_name);
                                    $('#conn-select').val('disabled', 'false');
                                    $('.btn-con').removeAttr('style');
                                    $(this).attr('style','background:lightblue');
                                    $('.connector-info').empty();
                                    for (var info in data[event.data.idx]) {
                                        var pTag = $('<p/>');
                                        pTag.html(info + ':&nbsp;' + data[idx][info]);
                                        $('.connector-info').append(pTag);
                                    }
                                });
                    $('.connector-list').append(buttonTag);
                }
            }
    );
});
</script>
{% endblock %}

datasets/templates/datasets/create_dataset.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}New Data set{% endblock %}

{% block nav-title %}<h3>New&nbsp;Data&nbsp;set</h3>{% endblock %}

{% block body %}
<div class="row">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Type</li>
                        <li class="breadcrumb-item active">Upload</li>
                        <li class="breadcrumb-item active">Preview</li>
                    </ol>
                </nav>
            </div>
            <div class="card-body">
                <a class="nav-item nav-link" href="{% url 'datasets:upload' %}">
                    <i class="fa fa-file"></i>&nbsp;File
                </a>
            </div>
            <div class="card-body">
                <a class="nav-item nav-link" href="{% url 'datasets:connector' %}">
                    <i class="fa fa-database"></i>&nbsp;Database
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

datasets/templates/datasets/dataset_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}Delete Confirm{% endblock %}

{% block nav-title %}<h3>Confirm</h3>{% endblock %}
{% block body %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.display_name }}"?</p>
    <input type="submit" value="Confirm" class="btn btn-danger" />
    <a href="javascript:history.back()" class="btn btn-default">Back</a>
</form>
{% endblock %}

datasets/templates/datasets/dataset_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block head %}Data sets{% endblock %}

{% block nav-title %}<h3>Data&nbsp;sets</h3>{% endblock %}

{% block datasets_active %}active{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a href="{% url 'datasets:import' %}" class="nav-link btn btn-primary">
                <i class="ti-plus"></i>&nbsp;
                <span class="d-lg-block">{% trans 'New' %}</span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle btn" href="#" id="searchDropdown" data-toggle="dropdown">
                <i class="ti-search"></i>&nbsp;
                <span class="d-lg-block">{% trans 'Search' %}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="ml-2 mr-2 mt-1 mb-1">
                <input type="text" class="form-control" placeholder="Search...">
                </div>
            </div>
        </li>
    </ul>
{% endblock %}
{% block body %}
    <div class="row">
    {% for dataset in dataset_list %}
    <div class="col-sm-12 col-md-6 col-xl-4">
        <div class="card card-stats">
            <div class="card-body">
                <div class="row">
                    <div class="col-5">
                            <div class="icon-big icon-warning text-center">
                                {% if dataset.external %}
                                <i class="ti-harddrives"></i>
                                {% else %}
                                <i class="ti-package"></i>
                                {% endif %}
                            </div>
                    </div>
                    <div class="col-7">
                        <a href="{% url 'datasets:detail' dataset.id %}">
                            <h3>
                                {{ dataset.display_name }}
                            </h3>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <p>&nbsp;{{ dataset.description }}</p>
                    </div>
                </div>
                <div class="card-footer">
                    <hr>
                    <div class="row">
                        <div class="col-12">
                            <div class="stats">
                                Created: {{ dataset.timestamp }}
                            </div>
                        </div>
                        <div class="col-10"></div>
                        <div class="col-1">
                            <div class="stats">
                                <a href="{% url 'datasets:delete' dataset.id %}">
                                    <div class="icon-danger">
                                    <i class="ti-trash"></i>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
{% endblock %}

{% block scriptblock %}
{% endblock %}

datasets/templates/datasets/preview.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block head %}Preview{% endblock %}

{% block nav-title %}<h3>Preview</h3>{% endblock %}

{% block linkblock %}
<link href="{% static 'datasets/css/ds-table.css' %}" rel="stylesheet" />
{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a href="javascript:;" onclick="$('#save_form').submit()" class="nav-link btn btn-success">
                <i class="ti-save"></i>
                {% trans 'Save' %}
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'datasets:cancel' %}?file_name={{ display_name }}" class="nav-link btn btn-default">{% trans 'Cancel' %}</a>
        </li>
    </ul>
{% endblock %}

{% block body %}
<div class="card">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'datasets:import' %}">Type</a></li>
            <li class="breadcrumb-item"><a href="{% url 'datasets:upload' %}">Upload</a></li>
            <li class="breadcrumb-item">Preview</li>
        </ol>
    </nav>
    <div class="card-body">
        <form id="save_form" method="post">
            {% csrf_token %}
            <input type="hidden" name="file_name" id="file_name" value="{{ file_name }}">
            <input type="hidden" name="schema" id="schema">
            <input type="hidden" name="extension" id="extension" value="{{ extension }}">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="display_name">Name</label>
                        <input type="text" name="display_name" id="display_name" class="form-control" value="{{ display_name }}">
                    </div>
                    <div class="form-group">
                        {% if sep %}
                        <label for="sep">Delimiter</label>
                        <input type="text" name="sep" id="sep" class="form-control" value="{{ sep }}">
                        {% else %}
                        <label for="sheet_name">Sheet name</label>
                        <input type="text" name="sheet_name" id="sheet_name" class="form-control" value="{{ sheet_name }}">
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        <label for="description">Description</label>
                        <input type="text" name="description" id="description" class="form-control" value="{{ description }}">
                    </div>
                    <div class="form-group">
                        <label for="encoding">Encoding</label>
                        <input type="text" name="encoding" id="encoding" class="form-control" value="{{ encoding }}">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col" style="overflow-x:auto;height: calc(100vh/2)">
        <table class="ds-table table table-striped">
            <thead>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
    <br>
<div class="row">
    <div class="col-sm-12 col-md-6">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-10">
                        <h5>Column Type</h5>
                    </div>
                    <div class="col-2">
                        <a class="nav-link" data-toggle="dropdown">
                            <i class="ti-menu"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-left">
                            <a class="dropdown-item" href="#">object</a>
                            <a class="dropdown-item" href="#">int64</a>
                            <a class="dropdown-item" href="#">date</a>
                        </div>
                    </div>
                </div>
                <hr>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-8" id="col-name"></div>
                    <div class="col-4" id="col-type"></div>
                </div>
            </div>
            <div class="card-footer">
                <div class="stats"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scriptblock %}
<script src="{% static 'datasets/js/ds-table.js' %}"></script>
<script>
    $(document).ready(function() {
        $('table tbody').on('mouseover mouseleave click', "td", function(e) {
            if (e.type == 'mouseover') {
                $("colgroup").eq($(this).index()).addClass("hover");
            }
            else if(e.type == 'mouseleave') {
                $("colgroup").eq($(this).index()).removeClass("hover");
            }
            else {
                $("colgroup").removeClass("selected");
                $("th").removeClass("first");
                $("td").removeClass("last");
                $("colgroup").eq($(this).index()).addClass("selected");
                $("th").eq($(this).index()).addClass("first");
                $("tr:last td").eq($(this).index()).last().addClass("last");
                var schema = JSON.parse($('#schema').val());
                var col = $("tr th").eq($(this).index()).html();
                $('#col-name').html(col);
                $('#col-type').html(schema[col]);
            }
        });

        $.get("{% url 'datasets:api_preview' %}",
            {
                "file_name": $('#file_name').val(),
                "display_name": $('#display_name').val(),
                "extension": $('#extension').val()
            },
            function(data, status){
                $('input#schema').val(JSON.parse(data.schema));
                addColGroup(data.columns, $('table'));
                buildTableHeader(data.columns, $('table thead'));
                buildTableBody(data.sample, $('table tbody'));
            }
        );

        $('input#sep, input#encoding').change(function(){
            $.get("{% url 'datasets:api_preview' %}",
                {
                    "file_name": $('#file_name').val(),
                    "display_name": $('#display_name').val(),
                    "sep": $('#sep').val(),
                    "encoding": $('#encoding').val(),
                    "columns": $('#columns').val(),
                    "description": $('#description').val()
                },
                function(data, status) {
                    resetTable($('table'));
                    addColGroup(data.columns, $('table'));
                    buildTableHeader(data.columns, $('table thead'));
                    buildTableBody(data.sample, $('table tbody'));
                });
        });
    });
</script>
{% endblock %}

datasets/templates/datasets/query.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block head %}Query{% endblock %}

{% block nav-title %}<h3>Query</h3>{% endblock %}

{% block linkblock %}
    <link href="{% static 'datasets/css/ds-table.css' %}" rel="stylesheet" />
{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a href="javascript:;" onclick="$('#save_form').submit()" class="nav-link btn btn-success">
                <i class="ti-save"></i>
                {% trans 'Save' %}
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link btn btn-default">{% trans 'Cancel' %}</a>
        </li>
    </ul>
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'datasets:import' %}">Type</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'datasets:connector' %}">Connector</a></li>
                    <li class="breadcrumb-item">Query</li>
                </ol>
            </nav>
        </div>
        <div class="card-body">
            <form id="save_form" method="post">
                {% csrf_token %}
                <input type="hidden" id="conn_name" value="{{ conn_name }}">
                <input type="hidden" name="schema" id="schema">
                <div class="row">
                    <div class="col">
                        <textarea id="query_string" name="query_string" class="form-control"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="display_name">Name</label>
                            <input type="text" name="display_name" id="display_name" class="form-control" value="{{ display_name }}">
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="description">Description</label>
                            <input type="text" name="description" id="description" class="form-control" value="{{ description }}">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col" style="overflow-x:auto;height: calc(100vh/2)">
            <table class="ds-table table table-striped">
                <thead>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-10">
                            <h5>Column Type</h5>
                        </div>
                        <div class="col-2">
                            <a class="nav-link" data-toggle="dropdown">
                                <i class="ti-menu"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-left">
                                <a class="dropdown-item" href="#">object</a>
                                <a class="dropdown-item" href="#">int64</a>
                                <a class="dropdown-item" href="#">date</a>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-8" id="col-name"></div>
                        <div class="col-4" id="col-type"></div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="stats"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scriptblock %}
<script src="{% static 'datasets/js/ds-table.js' %}"></script>
<script>
$(document).ready(function() {
   $('#query_string').change(function() {
       $.get("{% url 'datasets:api_query' %}",
           {
               "conn_name": $('#conn_name').val(),
               "sql": $(this).val()
           },
           function(data, status) {
               $('input#schema').val(JSON.parse(data.schema));
               resetTable($('table'));
               addColGroup(data.columns, $('table'));
               buildTableHeader(data.columns, $('table thead'));
               buildTableBody(data.sample, $('table tbody'));
           }
       );
   });
});
</script>
{% endblock %}