accounts/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from . import views, forms

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(template_name='accounts/login.html', authentication_form=forms.UserLoginForm), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='view_profile'),
    url(r'^profile/edit/$', views.EditProfileView.as_view(), name='edit_profile'),
    url(r'^profile/password/$', views.ProfilePasswordChangeView.as_view(), name='change_password'),
]

connectors/urls.py
from django.conf.urls import url
from . import views, viewsets

app_name = 'connectors'

urlpatterns = [
    url(r'^$', views.ConnectorListView.as_view(), name='list'),
    url(r'^create/$', views.CreateConnectorView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.UpdateConnectorView.as_view(), name='update'),
    url(r'^api/$', viewsets.ConnectorAPIView.as_view(), name='api_list'),
]

trigrams/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as root_views

urlpatterns = [
    url(r'^$', root_views.login_redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^connectors/', include('connectors.urls')),
    url(r'^datasets/', include('datasets.urls')),
]

connectors/models.py
from django.contrib.auth.models import User
from django.db import models


class Connector(models.Model):
    MYSQL = 'mysql'
    POSTGRE = 'postgresql'
    ORACLE = 'oracle'
    DB_TYPES = [
        (MYSQL, 'mysql'),
        (POSTGRE, 'postgresql'),
        (ORACLE, 'oracle'),
    ]
    conn_name = models.CharField(max_length=20)
    db_type = models.CharField(max_length=10, choices=DB_TYPES)
    host = models.CharField(max_length=200)
    port = models.IntegerField()
    username = models.CharField(max_length=20, blank=True)
    password = models.CharField(max_length=256, blank=True)
    db_instance = models.CharField(max_length=20)
    owner = models.ForeignKey(User)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.conn_name

connectors/forms.py
from django.utils.translation import ugettext
from django.contrib.auth.forms import forms
from .utils import create_connection

from .models import Connector


class CreateConnectorForm(forms.ModelForm):
    conn_name = forms.CharField(label=ugettext('Connection name'), widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Connection name'),
    }))
    db_type = forms.ChoiceField(label=ugettext('Type'), choices=Connector.DB_TYPES, widget=forms.Select(attrs={
        'class': 'form-control',
    }))
    host = forms.CharField(label=ugettext('Host'), widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Host'),
    }))
    port = forms.IntegerField(label=ugettext('Port'), widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Port'),
    }))
    username = forms.CharField(label=ugettext('Username'), required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Username'),
    }))
    password = forms.CharField(label=ugettext('Password'), required=False, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Password'),
    }))
    db_instance = forms.CharField(label=ugettext('Database'), widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Database'),
    }))

    def clean(self):
        cleaned_data = super().clean()
        try:
            create_connection(cleaned_data.get('db_type'),
                              cleaned_data.get('username'),
                              cleaned_data.get('password'),
                              cleaned_data.get('host'),
                              cleaned_data.get('port'),
                              cleaned_data.get('db_instance'))
        except:
            raise forms.ValidationError(
                ugettext('Can not connect to database with settings, please recheck settings again.'),
                code='invalid'
            )

    class Meta:
        model = Connector
        fields = [
            'conn_name',
            'db_type',
            'host',
            'port',
            'username',
            'password',
            'db_instance',
        ]


class UpdateConnectorForm(forms.ModelForm):
    db_type = forms.ChoiceField(label=ugettext('Type'), choices=Connector.DB_TYPES, widget=forms.Select(attrs={
        'class': 'form-control',
    }))
    host = forms.CharField(label=ugettext('Host'), widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Host'),
    }))
    port = forms.IntegerField(label=ugettext('Port'), widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Port'),
    }))
    username = forms.CharField(label=ugettext('Username'), required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Username'),
    }))
    password = forms.CharField(label=ugettext('Password'), required=False, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Password'),
    }))
    db_instance = forms.CharField(label=ugettext('Database'), widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': ugettext('Database'),
    }))

    def clean(self):
        cleaned_data = super().clean()
        try:
            create_connection(cleaned_data.get('db_type'),
                              cleaned_data.get('username'),
                              cleaned_data.get('password'),
                              cleaned_data.get('host'),
                              cleaned_data.get('port'),
                              cleaned_data.get('db_instance'))
        except:
            raise forms.ValidationError(
                ugettext('Can not connect to database with settings, please recheck settings again.'),
                code='invalid'
            )

    class Meta:
        model = Connector
        fields = [
            'db_type',
            'host',
            'port',
            'username',
            'password',
            'db_instance',
        ]

connectors/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Connector
from .forms import CreateConnectorForm, UpdateConnectorForm


class ConnectorListView(LoginRequiredMixin, ListView):
    context_object_name = 'connection_list'
    template_name = 'connectors/conn_list.html'
    login_url = reverse_lazy('accounts:login')

    def get_queryset(self):
        return Connector.objects.filter(owner=self.request.user)


class CreateConnectorView(LoginRequiredMixin, CreateView):
    form_class = CreateConnectorForm
    template_name = 'connectors/create_conn.html'
    login_url = reverse_lazy('accounts:login')

    def get_success_url(self):
        return reverse('connectors:list')

    def form_valid(self, form):
        connector = form.save(commit=False)
        connector.owner = self.request.user
        connector.save()
        return super(CreateConnectorView, self).form_valid(form)


class UpdateConnectorView(LoginRequiredMixin, UpdateView):
    model = Connector
    form_class = UpdateConnectorForm
    template_name = 'connectors/conn_detail.html'
    login_url = reverse_lazy('accounts:login')
    success_url = reverse_lazy('connectors:list')

connectors/templates/connectors/conn_detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}

{% block head %}{% trans 'Connector' %}{% endblock %}

{% block nav-title %}<h3>{{ object.conn_name }}</h3>{% endblock %}

{% block linkblock %}
{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a href="javascript:;" onclick="$('form').submit()" class="nav-link btn btn-success">
                <i class="ti-save"></i>
                {% trans 'Save' %}
            </a>
        </li>
        <li class="nav-item">
            <a href="javascript:history.back()" class="nav-link btn btn-default">{% trans 'Cancel' %}</a>
        </li>
    </ul>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

connectors/templates/connectors/conn_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block linkblock %}
    <link href="{% static 'datasets/css/ds-table.css' %}" rel="stylesheet" />
{% endblock %}

{% block head %}Connectors{% endblock %}

{% block connectors_active %}active{% endblock %}

{% block nav-title %}<h3>Connectors</h3>{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a href="{% url 'connectors:create' %}" class="nav-link btn btn-primary">
                <i class="ti-plus"></i>&nbsp;
                <span class="d-lg-block">{% trans 'New' %}</span>
            </a>
        </li>
    </ul>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-12 col-md-8">
        {% for conn in connection_list %}
        <div class="card card-tasks">
            <div class="card-header">
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="alert alert-info alert-with-icon">
                            <span class="fa fa-database" data-notify="icon"></span>
                            <span>{{ conn.conn_name }}</span>
                            <a href="{% url 'connectors:update' conn.pk %}" class="close">
                                <i class="fa fa-edit"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <hr>
                <div class="stats">
                    <i class="now-ui-icons loader_refresh spin"></i>
                    Updated: {{ conn.updated }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-sm-12 col-md-4">
        <div class="tab-content">
            {% for conn in connection_list %}
            <div class="tab-pane fade" id="detail_{{ conn.id }}">
                Uri: {{ conn.uri }} <br>
                Database: {{ conn.db_instance }}
            </div>
            {% endfor %}
        </div>
    </div>
    <div  class="col-4"></div>
</div>
{% endblock %}

connectors/templates/connectors/create_conn.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}

{% block head %}{% trans 'Create Connector' %}{% endblock %}

{% block nav-title %}<h3>Create&nbsp;Connector</h3>{% endblock %}

{% block linkblock %}
{% endblock %}

{% block navbar %}
<ul class="nav navbar-nav ml-auto">
    <li class="nav-item">
        <a href="javascript:;" onclick="$('form').submit()" class="nav-link btn btn-success">
            <i class="ti-save"></i>
            {% trans 'Save' %}
        </a>
    </li>
    <li class="nav-item">
        <a href="javascript:history.back()" class="nav-link btn btn-default">{% trans 'Cancel' %}</a>
    </li>
</ul>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}